# Underia Mod Setup
# Auto generated by src.mods.setup.underia_mod_setup()
# Copyright klpig 2024, all rights not reserved.

import underia, mods

# Basic datas
MOD_NAME = 'Underia Texture Reworked'
MOD_VERSION = (1, 0, 0)
MOD_AUTHOR = 'KLpig'
MOD_DESCRIPTION = 'Remake of original underia sb texture.(HQ4X!)'

# Mod Contents
ITEMS: dict[str, underia.Inventory.Item] = {
	
}
RECIPES: list[underia.Recipe] = [
	
]
WEAPONS: dict[str, underia.Weapon] = {
	
}
PROJECTILE_TYPE = type(underia.Projectiles.Projectile)
PROJECTILES: dict[str, PROJECTILE_TYPE] = {
	
}
ENTITY_TYPE = type(underia.Entities.Entity)
ENTITIES: dict[str, ENTITY_TYPE] = {
	
}

# SETUP_FUNC
# Code here (import allowed)
# SETUP_FUNC
# UPDATE_FUNC
# Code here (import allowed)
# UPDATE_FUNC
mods.wrap()