# Underia Mod Setup
# Auto generated by src.mods.setup.underia_mod_setup()
# Copyright klpig 2024, all rights not reserved.

from src import underia, mods

# Basic datas
MOD_NAME = 'God\'s Mod'
MOD_VERSION = (1, 0, 0)
MOD_AUTHOR = 'KLpig'
MOD_DESCRIPTION = 'Oh! It\'s the God!'

# Mod Contents
ITEMS: dict[str, underia.Inventory.Item] = {
	
}
RECIPES: list[underia.Recipe] = [
	
]
WEAPONS: dict[str, underia.Weapon] = {
	
}
PROJECTILE_TYPE = type(underia.Projectiles.Projectile)
PROJECTILES: dict[str, PROJECTILE_TYPE] = {
	
}
ENTITY_TYPE = type(underia.Entities.Entity)
ENTITIES: dict[str, ENTITY_TYPE] = {
	
}

game = underia.Game()
underia.write_game(game)
# SETUP_FUNC
# Code here (import allowed)
underia.get_game().player.hp_sys(op='config', immune=True)
# SETUP_FUNC
# UPDATE_FUNC
# Code here (import allowed)
# UPDATE_FUNC
mods.wrap()