# Underia Mod Setup
# Auto generated by src.mods.setup.underia_mod_setup()
# Copyright klpig 2024, all rights not reserved.

from src import underia, mods

# Basic datas
MOD_NAME = 'Terraria Resources Pack'
MOD_VERSION = (1, 0, 2)
MOD_AUTHOR = 'Klpig'
MOD_DESCRIPTION = 'Use terraria styled game'

# Mod Contents
ITEMS: dict[str, underia.Inventory.Item] = {
	
}
RECIPES: list[underia.Recipe] = [
	
]
WEAPONS: dict[str, underia.Weapon] = {
	
}
PROJECTILE_TYPE = type(underia.Projectiles.Projectile)
PROJECTILES: dict[str, PROJECTILE_TYPE] = {
	
}
ENTITY_TYPE = type(underia.Entities.Entity)
ENTITIES: dict[str, ENTITY_TYPE] = {
	
}

mods.wrap()