# Underia Mod Setup
# Auto generated by src.mods.setup.underia_mod_setup()
# Copyright klpig 2024, all rights not reserved.

import underia, mods

# Basic datas
MOD_NAME = 'Talented'
MOD_VERSION = (1, 0, 0)
MOD_AUTHOR = 'KLpig'
MOD_DESCRIPTION = 'Allow all skills'

# Mod Contents
ITEMS: dict[str, underia.Inventory.Item] = {
	
}
RECIPES: list[underia.Recipe] = [
	
]
WEAPONS: dict[str, underia.Weapon] = {
	
}
PROJECTILE_TYPE = type(underia.Projectiles.Projectile)
PROJECTILES: dict[str, PROJECTILE_TYPE] = {
	
}
ENTITY_TYPE = type(underia.Entities.Entity)
ENTITIES: dict[str, ENTITY_TYPE] = {
	
}

'''
# SETUP_FUNC
# Code here (import allowed)
import underia
pf = underia.get_game().player.profile
for k in pf.SKILL_DATA.keys():
    if k not in pf.select_skill:
        pf.select_skill.append(k)
# SETUP_FUNC
'''
# UPDATE_FUNC
# Code here (import allowed)
# UPDATE_FUNC
mods.wrap()