en_cn = {
    'accessory': '饰品',
    'mana': '法力',
    'mana cost': '法力消耗',
    'projectile': '投射物',
    'speed': '速度',
    'damage': '伤害',
    'knockback': '击退',
    'physical': '物理',
    'piercing': '穿透',
    'magical': '魔法',
    'melee': '近战',
    'ranged': '远程',
    'defense': '防御',
    'sec': '秒',
    'regeneration': '恢复',
    'touching': '接触',
    'night vision': '夜视',

    'ingot': '锭',
    'substance': '物质',
    'core': '核心',
    'mark': '印记',

    'wood': '木材',
    'wooden': '木',
    'leaf': '叶子',
    'copper': '铜',
    'iron': '铁',
    'steel': '钢',
    'platinum': '铂金',
    'cell organization': '细胞组织',
    'magic stone': '魔石',
    'blood': '血',
    'firite': '浴火',
    'mysterious': '神秘',
    'storm': '风暴',
    'soul': '灵魂',
    'evil': '邪恶',
    'soul of flying': '飞翔之魂',
    'soul of integrity': '诚实之魂',
    'soul of bravery': '勇气之魂',
    'soul of courage': '勇气之魂',
    'soul of kindness': '善良之魂',
    'soul of perseverance': '毅力之魂',
    'soul of will': '毅力之魂',
    'soul of patience': '耐心之魂',
    'soul of justice': '正义之魂',
    'soul of determination': '决心之魂',
    'palladium': '钯金',
    'mithrill': '秘银',
    'titanium': '钛金',
    'saint': '圣',

    'torch': '火炬',
    'night visioner': '夜视仪',
    'hammer': '锤',
    'furnace': '熔炉',
    'anvil': '铁砧',
    'shield': '盾牌',
    'bottle': '瓶',
    'necklace': '项链',
    'mystery': '神秘',
    'dark': '黑暗',
    'the': '',
    'spirit': '灵魂',
    'book': '书',
    'weak': '弱',
    'healing potion': '治疗药水',
    'magic potion': '魔法药水',
    'firy plant': '火焰植物',
    'suspicious eye': '可疑眼睛',
    'fire slime': '火焰史莱姆',
    'wind': '风',
    'mechanic': '机械',
    'electric': '电子',
    'eye': '眼',
    'worm': '蠕虫',
    'unit': '元件',
    'spider': '蜘蛛',
    'watch': '表',
    'energy': '能量',

    'sword': '剑',
    'blade': '刃',
    'spear': '矛',
    'magic_sword': '魔剑',
    'magic_blade': '魔刃',
    'bloody': '血腥',
    'volcano': '火山',
    'sand': '沙',
    'night\'s edge': '永夜刃',
    'spiritual': '灵魂',
    'stabber': '刺探者',
    'balanced': '平衡',
    'bow': '弓',
    'recurve bow': '反曲弓',
    'piercer': '穿刺者',
    'discord storm': '混乱风暴',
    'pistol': '手枪',
    'rifle': '步枪',
    'submachine gun': '霰弹枪',
    'magma': '熔岩',
    'assaulter': '突击者',
    'shadow': '影',
    'arrow': '箭',
    'magic': '魔',
    'bullet': '子弹',
    'plasma': '脑浆',
    'rock': '岩石',
    'shadow bullet': '暗影子弹',
    'glowing splint': '火花木棒',
    'wand': '魔杖',
    'burning book': '燃烧之书',
    'talent book': '天赋之书',
    'hematology': '血液学',
    'midnight\'s wand': '午夜魔杖',
    'night\'s pike': '夜之枪',
    'destroyer': '毁灭者',
    'daedalus': '代达罗斯',
    'stormbow': '风暴弓',
    'true': '真',
    'excalibur': '圣剑',
    'gun': '枪',
    'quick': '迅捷',
    'dangerous': '危险',
    'terrified': '恐惧',
    'sheath': '剑鞘',
    'quiver': '箭袋',
    'hat': '帽子',
    'helmet': '头盔',
    'cloak': '披风',
    'pluvial': '斗篷',
    'ring': '戒指',
    'orange': '橙色',
    'yellow': '黄色',
    'green': '绿色',
    'blue': '蓝色',
    'purple': '紫色',
    'red': '红色',
    'cyan': '青色',
    'aimer': '瞄准者',
    'windstorm': '风暴',
    'winds': '风',
    '\'s': '',
    '\'': '',
    'swordman': '剑士',
    'assassin': '刺客',
    'warlock': '术士',
    'paladin': '圣骑士',
    'wings': '翅膀',
    'honest flyer': '诚实的飞行者',
    'crabapple': '螃果',
    'butterscotch pie': '奶油肉桂派',
    'seatea': '海茶',
    'heart': '心',
    'crystal': '水晶',
    'glove': '手套',
    'arcane': '奥术',
    'curse': '诅咒',
    'gravity': '重力',
    'forbidden curse: ': '禁咒·',
    'perseverance sword': '毅力之剑',
    'will sword': '毅力之剑',
    'black hole': '黑洞',
    'time': '时间',

    'armor': '护甲',
    'usage of major accessory': '主要饰品使用率',
    'inspiration': '灵感值',
    'karma': '善业',
    'touch': '碰撞',
    'reduction': '衰减',
    'mass': '质量',
    'friction': '摩擦',
    'underia': 'underia',
    'sprint': '冲刺',
    'distance': '距离',
    'cost': '消耗',
    'flashback': '回溯',
    'deconstruction': '分解',
    'lysis': '裂变',
    'disintegrator': '分解射线',
    'floating': '漂浮',
    'climax': '「峰」',
    'turning point': '「转」',
    'galaxy': '星河',
    'highlight': '高光',
    'fountain': '喷泉',
    'star of devotion': '神圣之星',
    'relevation of cycle': '轮回之誓',
    'snare': '军鼓',
    'apple': '苹果',
    'smells good': '香',
    'watcher': '守望者',
    'bell': '铃',
    'holy': '圣',
    'holy stormer': '风暴圣响',
    'prayer': '祈祷',
    'penalty': '罚',
    'heal': '治疗',
    'bible': '圣经',
    'gray': '灰色',
    'black': '黑色',
    'heating': '加热',
    'cooling': '冷却',
    'dance of': '魔舞：',
    'cross': '十字',
    'mechanical': '机械',
    'plastic flower': '塑料花',
    'huge snowball': '巨型雪球',
    'murderer': '谋杀者',
    'knife': '刀',
    'savior': '救世主',
    'dragon horn': '龙吟号角',
    'wild': '野生',
    'fluffball': '绒球',
    'sky painting': '天之画',
    'metal food': '金属食品',
    'suspicious': '可疑',
    'jevil': '混沌·小丑魔',
    'statue': '雕塑',
    'metal': '金属',
    'metal hand': '金属指针',
    'accelerationism': '加速主义',
    'shackle': '束缚',
    'uncanny valley': '恐怖谷',
    'snowman piece': '雪人片',
    'legendary hero': '传奇英雄',
    'shard': '碎片',
    'sleep eye': '睡眼',
    'pacifier': '安抚者',
    'amulet': '护身符',
    'integrity': '诚实',
    'bravery': '勇气',
    'perseverance': '毅力',
    'patience': '耐心',
    'sleep': '睡眠',
    'splint': '木棒',
    'shine': '耀',
    'note sheet': '音符纸',
    'magician': '魔法师',
    'karmic': '因果',
    'flower': '花',
    'ore': '矿石',
    'stone altar': '石祭坛',
    'altar': '祭坛',
    'swift': '迅捷',
    'armed': '装甲',
    'chest': '箱',
    'corruption': '腐化',
    'demand': '欲望',
    'reinforce': '强化',
    'lifelong': '长命',
    'elite': '精英',
    'summon': '召唤',
    'kill': '击败',
    'summon and kill': '召唤并击败',
    'recipe': '配方',
    'endless': '无尽',
    'fireball': '火球',
    'dragon': '龙',
    'dragon scale': '龙鳞',
    'a ': '一个',
    'especially': '尤其',
    'resistant to': '能够抵抗',
    'light': '光',
    'fire': '火',
    'ice': '冰',
    'fire quench: dragon': '火龙淬：',
    'ice quench: dragon': '冰龙淬：',
    'dark quench: dragon': '暗龙淬：',
    'light quench: dragon': '光龙淬：',
    'swift sword': '西洋剑',
    'octave': '八度',
    'when first hit': '首次击中时',
    'get back': '返还',
    'of': '',
    'gain ally with': '增益我方',
    'dragon breath': '龙息',
    'lv.i': '壹階',
    'lv i': '壹階',
    'lv.ii': '贰階',
    'lv ii': '贰階',
    'lv.iii': '叁階',
    'lv iii': '叁階',
    'lv.iv': '肆階',
    'lv iv': '肆階',
    'lv.v': '伍階',
    'lv v': '伍階',
    'lv.vi': '陆階',
    'lv vi': '陆階',
    'lv.vii': '柒階',
    'lv vii': '柒階',
    'lv.xx': '终階',
    'lv xx': '终階',

    'a line start, a god\'s fall': '一语起，一神落',
    'magister': '魔导师',
    'shoots': '发射',
    'a row of': '一行',
    'the ruling sword': '裁决之剑',
    'very': '非常',
    'increase your': '提升',
    'mentality': '精神力',
    'additional': '额外',
    'maximum': '最大',
    'hero shaped': '英雄形状的',
    'recover': '回复',
    'and': '并,',
    'add': '新增',
    'joker evil': '小丑魔',
    'poet bonus': '游吟诗人增益',
    'worldsaver': '救世者',
    'hallow': '神圣',
    'pacify': '安抚',
    'it can save the world': '它可以拯救世界',
    'chaos': '混乱',
    'attack': '攻击',
    'earth': '土',
    'obsidian': '黑曜石',
    'magnificent': '壮丽',
    'natural': '自然',
    'ignite': '点燃',
    'air': '风',
    'thief': '盗贼',
    'small': '小型',
    'tower shield': '塔型盾',
    'gorgeous': '绝美',
    'forest': '森林',
    'coniferous': '针叶',
    'fur': '毛皮',
    'several': '数个',
    'each': '每个',
    'dealing': '造成',
    'fluffy': '毛绒',
    'fairy': '仙灵',
    'hermes': '赫尔墨斯',
    'grenade king': '手雷王',
    'jade face': '玉面',
    'enable': '启用',
    'scattering': '散射',
    'dawn': '黎明',
    'shortsword': '短剑',
    'twilight': '暮光',
    'twinsword': '双剑',
    'twinblade': '双刃',
    'broadsword': '阔剑',
    'soarer': '翱翔者',
    'destroy': '摧毁',
    'enhance': '提升',
    'to ': '以',
    'make it under': '使其在于',
    'death': '死亡',
    'life': '生命',
    'broken': '破损',
    'guardian': '守卫者',
    'star': '星',
    'glowing': '闪耀',
    'in ': '于',
    'tough': '坚硬',
    'forward': '脉冲',
    'water': '水',
    'not the others': '无他',
    'pong': '乒乒乓乓',
    'nobody left': '无人生还',
    'empty': '空',
    'shotgun': '霰弹枪',
    'three': '三个',
    'thousand': '千',
    'ignore': '忽略',
    'justice': '正义',
    'justice shot': '正义之枪',
    'chlorophyte': '叶绿',
    'lazer': '激光',
    'prism': '棱镜',
    'light focus': '光聚焦',
    'talent': '智力',
    'god': '神',
    'space': '空间',
    'all': '全部',
    'photon': '光子',
    'thorn': '荆棘',
    'super': '超',
    'thinking': '思想',
    'demon': '恶魔',
    'rune': '符文',
    'lifebringer': '生命使者',
    'great': '大',
    'remote': '远程',
    'mighty': '伟大',
    'of this blade is not necessary to say': '于这把剑中无需多言',
    'terror': '恐怖',
    'primal': '原初',
    'circulate': '循环',
    'domain': '领域',
    'determined': '决心',
    'determination': '决心',
    'matter': '物质',
    'ultradense': '致密',
    'your': '',
    'footprint': '足迹',
    'will': '会',
    'deal': '造成',
    'willpower': '意志',
    'ultra-lightspeed': '超光速',
    'karmic trail boots': '因果循迹重靴',
    'grasp of the infinite corridor': '无尽回廊之握',
    'fate alignment amulet': '命运校准护身符',
    'my locket': '我的挂坠盒',
    'my': '我的',
    'galaxy broad sword': '星河大剑',
    'eternal echo': '永恒回响',
    'musician': '音乐家',
    'phantom': '幻影',
    'sight': '视力',
    'essence of': '精华来自于',
    'strong': '强大',
    'church': '教堂',
    'colourful': '多彩',
    'strength': '力量',
    'wither': '凋零',
    'cold': '冰冷',
    'mind': '心灵',
    'cyber': '赛博',
    'dragon bone': '龙骨',
    'dragon skull': '龙颅',
    'dragon heart': '龙心',
    'bone': '骨',
    'skull': '颅',
    'merged metal': '融合金属',
    'finale': '大结局',
    'godkiller': '弑神者',
    'legging': '护腿',
    'headgear': '头饰',
    'mask': '面具',
    'plate mail': '板甲',
    'chestplate': '胸甲',
    'greaves': '护腿',
    'abyss': '深渊',
    'twin': '双子',
    'godfall': '神陨',
    'ice and fire': '冰与火',

    'ignis': '伊格尼斯',
    'scorching wing': '炽焰之翼',
    'northrend': '诺森德',
    'frost breath': '极寒之息',
    'nefarian': '纳法利安',
    'shadow embrace': '暗影之拥',
    'olivia': '奥利维亚',
    'radiance of light': '圣光之耀',
    'cybress': '赛博斯',
    'iron heart': '钢铁之心',
    'eonar': '艾诺尔',
    'whisper of mind': '心灵之语',
    'thing': '事物',
    'pickaxe': '镐',
    'critical': '暴击',
    'faith': '「信」',
    'clock': '「时」',
    'matters': '「物」',
    'the world\'s tree': '「世界之树」',
    'reincarnation': '轮回',
    'god\'s eye': '「神之眼」',

    'eternal hush': '永寂渊声',
    'voidstride treads': '渊行履迹',
    'vermillion sigil palms': '赤曜纹枢',
    'aurora dawn': '启明渊声',

    'air resistance': '空气阻力',
    'wing control': '翅膀控制',
    'walking tree': '行走之树',
    'chance': '机会',
    'save a ammo': '保存弹药',
    'reduce': '减少',
    'be ': '',
    'default': '一般',
    'common': '普通',
    'uncommon': '稀有',
    'rare': '罕见',
    'very rare': '非常罕见',
    'proficiency-made': '专家之作',
    'epic': '史诗',
    'legendary': '传说',
    'masterwork': '大师之作',
    'supreme': '至尊',
    'mythic': '神话',
    'super mythic': '超神话',
    'godlike': '神级',
    'super godlike': '超神级',

    'the fluffy worm': '毛绒的蠕虫',
    'the watcher of terror': '恐怖的守望者',
    'the god\'s heritage': '神的遗物',
    'the fire monster': '火焰的怪物',
    'the ghost of desert': '沙漠的幽魂',
    'the dimensional intruder': '次元的入侵者',
    'the contanminated destroyer': '腐化的毁灭者',
    'the cursed fairy': '诅咒的仙灵',
    'the ghost of the snowland': '极地的幽魂',
    'fire dragon': '火龙',
    'ice dragon': '冰龙',
    'dark dragon': '暗龙',
    'light dragon': '光龙',
    'mechanic dragon': '械龙',
    'mind dragon': '灵龙',
    'the heaven intruder': '天堂的入侵者',
    'the non-believer': '不实者',
    'the dishonester': '不诚者',
    'the metal worm of strength': '强力的金属虫',
    'the electric lier': '电子欺诈者',
    'the final mechanic': '最终的机械',
    'the greedy biter': '贪婪的啃食者',
    'follower of the truth': '真理的信徒',
    'the world\'s devourer': '世界的吞噬者',
    'the chaos laughter': '混乱的笑柄',
    'the semi-god': '半神',
    'the watcher of ages': '岁月的守望者',
    'the constructor': '初诞者',
    'sun and moon': '日与月',
    'the unwill of the supreme': '至高的不甘',
    'the end of shapeless': '无形的尽头',
    'the void and chaos': '虚无与混沌',

    'oblivion: annihilator': '终焉：湮灭之主',
    'end\'s sphere': '末世之球',
    'burst ball': '爆裂球',
    'crush ball': '碎裂球',

    'tip': '纸条',
    'done': '完成',
    'map': '地图',
    'weapon sweep': '武器扫荡',
    'image': '图像',
    'mem': 'MEM',
    'saving': '保存',
    'entity': '实体',
    'require': '需要',
    'any': '任何',
    'out': '出',
    'item': '物品',
    'collection': '收集',
    'fps': 'FPS',
    'x': 'x',
    'agility': '敏捷',
    'cd': 'CD',
    'deg': '度',
    'kg': '千克',
    'ize': '化',
    'good': '好',
    'rapid': '密集',
    'rocket': '火箭',
    'launcher': '发射器',
    'ammo': '弹药',
    'thrower': '投掷者',
    'you': '你',
    'improve': '改善',
    'd ': '',
    'save': '節省',

    'resolution': '「收」',
    'rising action': '「承」',
    'falling action': '「合」',

    'can only be placed in the first slot': '只能放在第一饰品栏',
    'can only be placed in the second slot': '只能放在第二饰品栏',
}
