en_cn = {
    'accessory': '饰品',
    'mana': '法力',
    'mana cost': '法力消耗',
    'projectile': '投射物',
    'speed': '速度',
    'damage': '伤害',
    'knockback': '击退',
    'physical': '物理',
    'mod:': '模组-',
    'crafting': '合成',
    'craftable': '可合成',
    'piercing': '穿透',
    'magical': '魔法',
    'melee': '近战',
    'ranged': '远程',
    'defense': '防御',
    'sec': '秒',
    'regeneration': '恢复',
    'touching': '接触',
    'night vision': '夜视',

    'ingot': '锭',
    'substance': '物质',
    'core': '核心',
    'mark': '印记',

    'wood': '木材',
    'wooden': '木',
    'leaf': '叶子',
    'copper': '铜',
    'iron': '铁',
    'cobalt': '钴蓝',
    'steel': '钢',
    'silver': '银',
    'platinum': '铂金',
    'zirconium': '锆石',
    'sky': '天',
    'ranseur': '镗',
    'cell organization': '细胞组织',
    'magic stone': '魔石',
    'blood': '血',
    'floatstone': '浮石',
    'firite': '浴火',
    'mysterious': '神秘',
    'storm': '风暴',
    'soul': '灵魂',
    'evil': '邪恶',
    'soul of flying': '飞翔之魂',
    'soul of integrity': '诚实之魂',
    'soul of bravery': '勇气之魂',
    'soul of courage': '勇气之魂',
    'soul of kindness': '善良之魂',
    'soul of perseverance': '毅力之魂',
    'soul of will': '毅力之魂',
    'soul of patience': '耐心之魂',
    'soul of justice': '正义之魂',
    'soul of determination': '决心之魂',
    'spirit essence': '魂精',
    'incremental': '增长',
    'ascendant spirit essence': '化神魂精',
    'world\'s lord': '世界之主',
    'world': '世界',
    'palladium': '钯金',
    'mithrill': '秘银',
    'titanium': '钛金',
    'saint': '圣',

    'torch': '火炬',
    'night visioner': '夜视仪',
    'hammer': '锤',
    'furnace': '熔炉',
    'anvil': '铁砧',
    'shield': '盾牌',
    'bottle': '瓶',
    'necklace': '项链',
    'mystery': '神秘',
    'dark': '黑暗',
    'the': '',
    'spirit': '灵魂',
    'book': '书',
    'weak': '弱',
    'healing potion': '治疗药水',
    'magic potion': '魔法药水',

    'crysanths': '草兰菊',
    'winteraceae': '寒冬青',
    'dendrobium': '砂岩斛',
    'flamaureus': '耀斑花',
    'gypsophila': '天蓝草',
    'vitaflora': '涅槃蕨',

    'firy plant': '火焰植物',
    'suspicious eye': '可疑眼睛',
    'fire slime': '火焰史莱姆',
    'wind': '风',
    'mechanic': '机械',
    'electric': '电子',
    'eye': '眼',
    'worm': '蠕虫',
    'unit': '元件',
    'spider': '蜘蛛',
    'watch': '表',
    'energy': '能量',

    'sword': '剑',
    'blade': '刃',
    'spear': '矛',
    'magic_sword': '魔剑',
    'magic_blade': '魔刃',
    'bloody': '血腥',
    'volcano': '火山',
    'sand': '沙',
    'night\'s edge': '永夜刃',
    'spiritual': '灵魂',
    'stabber': '刺探者',
    'balanced': '平衡',
    'bow': '弓',
    'recurve bow': '反曲弓',
    'piercer': '穿刺者',
    'discord storm': '混乱风暴',
    'power of disarray': '无序之力',
    'the law of nirvana is staying inside': '涅槃的法则在其中流淌',
    'viper\'s breath': '毒蛇之息',
    'the wingdings from the starry sky': '星空之怒',
    'try to use it': '拿起他',
    'sometimes you cannot handle this': '有时你可能控制不了他',
    '"cutting" enemies will freeze them and they will receive double damage': '截破恶敌，在双倍的伤害中凝冰',
    'able to': '可以',
    'mine': '挖掘',
    'damage increases within progress': '旅人在升华中成长',
    'merry christmas': '祝 圣诞快乐',
    'notebook a' : '笔记A',
    'seven souls\' light': '七魂耀',
    'circulates': '循环',
    'clockwise': '顺时针',
    'anticlockwise': '逆时针',
    'wield': '束缚',
    'wildsands': '狂沙',
    'oceanic current': '洋流',
    'ocean current': '洋流',
    'seedler': '种子弯刀',
    'sealed oath': '禁忌之誓',
    'combination of souls': '魂之华精',
    'minepower': '镐力',
    'event': '事件',
    'low mana': '低法力',
    'task & event': '任务&事件',
    'minutes': '分钟',
    'dt': 'D.T.',
    'nature': '源质',
    'shiny': '闪耀',
    'it acts as a stable "cash" for trading': '其于世界中被作为一个稳定的「货币」。',
    'place for storage': '存储容器',
    'it suppose to recover you': '它该让你回复生命的。',
    'mp': 'MP',
    'sea pearl': '海棱珠',
    'power to break the rules': '破灭规则的力量',
    'devil': '恶魔',
    'some': '一些',
    'ores': '矿石',
    'a powerful, eatable candy': '强力且可食用的糖',
    'hit or strike will "cut" off enemies': '次攻击或蓄力可以截断敌人的本源',
    'hp': 'HP',
    'new': '新',
    'what is it used for': '这能干嘛',
    'cauldron': '坩锅',
    'not found(bushi': '找不到(doge',
    'fast': '快速',
    'sword phantom': '剑影',
    'isn\'t': '不是',
    'end of anything': '任何事物的终止',
    'full in chaos': '充满混沌',
    'burning tears': '炎泪',
    'when hit': '当击中时',
    'steal extra': '偷取额外',
    'from target': '于目标',
    'the power of the evil and the hallow are balanced': '正邪之力已然均衡',
    'hellsell': '镇狱',
    'fire of fear silently burns': '恐惧之炎无声燃烧',
    'you are safe now': '你安全了',
    'angels tears': '天使之泪',
    'slow': '慢',
    'piercive': '具穿透性',
    'eternal sunfire': '永恒灼炎',
    'sprints toward enemy': '向敌人冲刺',
    'effects increases in water bodies or shallow abyss': '该效果于水中或深渊深层显著提升',
    'freeze': '冻结',
    'or': '或',
    'enemy': '敌人',
    'enemies': '敌人',
    'adherent': '信徒',
    'leading ray': '引领之光',
    'varies with time': '随时间变化',
    'state ii': 'II 态',
    'state i': 'I 态',
    'impossible to': '无法',
    'if is': '如果是',
    'as': '作',
    'vortex spike': '涡流之刺',
    'club': '梅花',
    'invisible': '隐形',
    'stats': '数值',
    'battlegear': '战铠',
    'ember': '余烬',
    'explode': '爆炸',
    'to pieces': '成碎片',
    'in air': '，于空中',
    'after': '经过',
    'that': '那些',
    'are burnt': '化为飞灰',
    'different speeds': '不同速度',
    'retribution': '业报',
    'from': '从',
    'from the sky': '从天而降',
    'the desert eagle': '「沙漠之鹰」',
    'night': '夜',
    'face to': '朝向',
    'mana erupt': '魔能喷涌',
    'newton': '牛顿',
    'chlorommo': '叶绿弹',
    'shoot': '发射',
    'three times': '三次',
    'chaos annihilator': '混沌破灭',
    'eterrow': '恒箭',
    'at once': '于一瞬',
    'wavic': '波箭',
    'bullets': '子弹',
    'burst': '爆发',
    'ages of life passed': '多少年经过',
    'venus magnum': '维纳斯万能枪',
    'i saw all you did': '我全都看到了',
    'nothing': '没事',
    'and the news always comes': '新者皆来',
    'spawning': '生成',
    'thermality': '热弹',
    'scarlett': '猩红',
    'furious': '发毛',
    'pressure': '压力',
    'love': '爱',
    'poet': '诗人',
    'with the following effect': '以以下效果',
    'lucky': '幸运',
    'following the enemy': '追随敌人',
    'limitless': '无限',
    'to enemy nearby': '于附近敌人',
    'hypnotist': '催眠',
    'spade': '黑桃',
    'noname': '无名',
    'tree': '树',
    'oboe': '双簧管',
    'huge': '巨',
    'priest': '牧师',
    'scale': '鳞甲',
    'hood': '兜帽',
    'traveller': '旅者',
    'vocalist': '歌者',
    'artist': '艺术家',
    'everscorch': '永炎',
    'stardream': '星梦',
    'tidal': '潮汐',
    'plaguebringer': '瘟疫使者',
    'shabby': '褴褛',
    'crown': '皇冠',
    'decreases': '降低',
    'non-': '非',
    'clear': '清澈',
    'immune to': '免疫',
    'effect of': '效果如',
    'darken': '暗化',
    'enlighten': '耀化',
    'effect from': '效果来自',
    'mana drain': '魔力干渴',
    'its': '它的',
    'clover': '三叶草',
    'critically': '暴击地',
    'tsunamic': '海啸',
    'tsunami': '海啸',
    'diving': '深潜',
    'wing boots': '翼靴',
    'sweep': '横扫',
    'hell': '地狱',
    'giantshield': '巨盾',
    'times': '倍',
    'glasses': '眼睛',
    'y:': ' -[Y] ',
    'projectiles': '投射物',
    'to the enemies': '面向敌人',
    'arrayed': '有序',
    'immune to all debuffs dealt by biomes': '对所有群系的减益免疫',
    'including': '包括',
    'jevil\'s tail': '小丑魔的尾巴',
    'tentacle': '触手',
    'cloudy': '云化',
    'scarf': '围巾',
    'damage received': '收到的伤害',
    'eye lens': '眼睛片',
    'dodge from': '躲避',
    'attacks': '攻击',
    'highspeed': '高速',
    'world\'s seed': '世界之种',
    'allows using [SHIFT] or [SPACE] to control speed': '可使用 [SHIFT] 或 [SPACE] 键来控制速度',
    'never give up': '永不言弃',
    'the willpower of courage': '勇气之意志',
    'menace': '威胁',
    'dodge rate': '闪避率',
    'wrath': '暴怒',
    'deal damages to you and nearby enemies': '对你和身边的敌人造成伤害',
    'endless power of fire': '无尽火之力',
    'cold present': '【冷】笑话',
    'mend players defense immediately': '修复破甲',
    'heaven goblins': '天国哥布林',
    ':h': ' [H]',
    ':m': ' [M]',
    'seed': '种',
    'burnt pan': '烧焦平底锅',
    'anemovitis': '风暴藤',
    'regenerative': '可再生',
    'twin eyes': '双子魔眼',
    'white guard': '雪白守卫',
    'the finale is the the start': '终焉亦为开始',
    'if it grows to': '若其长成',
    'greed': '贪婪',
    'fluffff': '毛毛毛毛虫',
    'magma king': '熔岩之主',
    'world\'s fruit': '世界之果',
    'reaches': '抵达',
    'your talent will come to a significant increase': '智力值将显著增加',
    'magic bulb': '魔法花苞',
    'joker': '【红王】',
    'origin bulb': '本源花苞',
    'candlefire': '烛火',
    'monument': '纪念碑',
    'legend': '神话',
    'is this, the god': '这，便是神明吗',
    'sky tri-kubes': '天空三立方',
    'press q': '按下 [Q] ',

    'before': '前',
    'gain': '增强',
    'daily apple, daily non-doctor': '每日一苹果，医生远离我',
    'a few': '一些',
    'pistol': '手枪',
    'rifle': '步枪',
    'submachine gun': '霰弹枪',
    'magma': '熔岩',
    'assaulter': '突击者',
    'shadow': '影',
    'arrow': '箭',
    'magic': '魔法',
    'bullet': '子弹',
    'plasma': '脑浆',
    'rock': '岩石',
    'shadow bullet': '暗影子弹',
    'glowing splint': '火花木棒',
    'wand': '魔杖',
    'burning book': '燃烧之书',
    'talent book': '天赋之书',
    'hematology': '血液学',
    'midnight\'s wand': '午夜魔杖',
    'dark spider lily': '曼魇沙华',
    'night\'s pike': '夜之枪',
    'destroyer': '毁灭者',
    'daedalus': '代达罗斯',
    'stormbow': '风暴弓',
    'true': '真',
    'excalibur': '契约与胜利之剑',
    'forbidden_oath': '契约与禁忌之剑',
    'gun': '枪',
    'quick': '迅捷',
    'dangerous': '危险',
    'terrified': '恐惧',
    'sheath': '剑鞘',
    'quiver': '箭袋',
    'hat': '帽子',
    'helmet': '头盔',
    'cloak': '披风',
    'pluvial': '斗篷',
    'ring': '戒指',
    'orange': '橙色',
    'yellow': '黄色',
    'green': '绿色',
    'blue': '蓝色',
    'purple': '紫色',
    'red': '红色',
    'cyan': '青色',
    'aimer': '瞄准者',
    'windstorm': '风暴',
    'winds': '风',
    '\'s': '',
    '\'': '',
    'swordman': '剑士',
    'assassin': '刺客',
    'warlock': '术士',
    'paladin': '圣骑士',
    'wings': '翅膀',
    'honest flyer': '诚实的飞行者',
    'crabapple': '螃果',
    'butterscotch pie': '奶油肉桂派',
    'seatea': '海茶',
    'heart': '心',
    'crystal': '水晶',
    'glove': '手套',
    'arcane': '奥术',
    'curse': '诅咒',
    'gravity': '重力',
    'forbidden curse: ': '禁咒·',
    'perseverance sword': '毅力之剑',
    'will sword': '毅力之剑',
    'black hole': '黑洞',
    'time': '时间',

    'murder core': '屠杀之核',
    'blood value': '血值',
    'locked': '锁定',
    'unlocked': '解锁',
    'murder level': '杀戮等级',
    'till': '直到',
    'ability': '能力',
    'locked to': '锁定于',
    'karma poison': '业果剧毒',
    'karma erosion': '恶业之蚀',
    'armor': '护甲',
    'usage of major accessory': '主要饰品使用率',
    'inspiration': '灵感值',
    'karma': '善业',
    'touch': '碰撞',
    'reduction': '衰减',
    'mass': '质量',
    'friction': '摩擦',
    'underia': 'underia',
    'sprint': '冲刺',
    'distance': '距离',
    'cost': '消耗',
    'flashback': '回溯',
    'deconstruction': '分解',
    'lysis': '裂变',
    'disintegrator': '分解射线',
    'floating': '漂浮',
    'climax': '「峰」',
    'turning point': '「转」',
    'galaxy': '星河',
    'highlight': '高光',
    'fountain': '喷泉',
    'star of devotion': '神圣之星',
    'relevation of cycle': '轮回之誓',
    'snare': '军鼓',
    'apple': '苹果',
    'smells good': '香',
    'watcher': '守望者',
    'bell': '铃',
    'holy': '圣',
    'holy stormer': '风暴圣响',
    'prayer': '祈祷',
    'penalty': '罚',
    'heal': '治疗',
    'bible': '圣经',
    'gray': '灰色',
    'black': '黑色',
    'heating': '加热',
    'cooling': '冷却',
    'dance of': '魔舞：',
    'cross': '十字',
    'mechanical': '机械',
    'plastic flower': '塑料花',
    'huge snowball': '巨型雪球',
    'murderer': '谋杀者',
    'knife': '刀',
    'savior': '救世主',
    'dragon horn': '龙吟号角',
    'wild': '野生',
    'fluffball': '绒球',
    'sky painting': '天之画',
    'metal food': '金属食品',
    'suspicious': '可疑',
    'jevil': '混沌·小丑魔',
    'plantera': '畸变·世纪之花',
    'plantera bulb': '世纪之花苞',
    'the friendliest mercy': '最亲切的救赎',
    'final': '终焉',
    'some says the time will be reversed when the speed is fast enough': '传说速度至登峰造极之时，因果倒逆，时光倒转',
    'heart locket': '心形挂坠盒',
    'reaches the highest, drop till the lowest': '登峰造极，由顺转衰，尸骨无存',
    'until everything\'s solved, the hidden one appears': '直至万事已解，幕后者现',
    'start chapter': '开始 CH.',
    'the finale is the start.': '我至终幕，为何又不是开始？',
    'your finale of this journey': '旅人回乡之终幕',
    'shield of recovery': '复苏之护',
    'the crush and demolish in the world': '原初世界之毁灭',
    'strike to throw it': '蓄力以扔出',
    'chaoticly sacrifice enemies in freeze, wither and bleeding': '混沌之物在绝望中燃烧、迷失、凋零',
    'damage and size increases within progress': '伴随旅人的每一刻',
    'thermal': '热源',
    'float': '浮',
    'it means of a start of a genocide': '杀戮之始',
    'water\'s breath': '水之呼吸',
    'always': '总是',
    'face to target': '指向目标',
    'expected death': '预期之死',
    'wave': '波',
    'hallowed': '圣源',
    'inventory': '背包',
    'leggings': '护腿',
    'glimmer skate': '微光曙鳐',
    'christmas': '圣诞',
    'christmas tree': '圣诞树',
    'candy cane': '糖果棒',
    'ginger bread': '姜饼',
    'everscream': '常绿尖啸怪',
    'statue': '雕塑',
    'metal': '金属',
    'metal hand': '金属指针',
    'accelerationism': '加速主义',
    'shackle': '束缚',
    'uncanny valley': '恐怖谷',
    'snowman piece': '雪人片',
    'legendary hero': '传奇英雄',
    'shard': '碎片',
    'sleep eye': '睡眼',
    'pacifier': '安抚者',
    'amulet': '护身符',
    'integrity': '诚实',
    'bravery': '勇气',
    'perseverance': '毅力',
    'patience': '耐心',
    'sleep': '睡眠',
    'splint': '木棒',
    'shine': '耀',
    'note sheet': '音符纸',
    'magician': '魔法师',
    'karmic': '业果',
    'flower': '花',
    'ore': '矿石',
    'sunken': '沉沦',
    'fly': '飞翔',

    'stone altar': '石祭坛',
    'altar': '祭坛',
    'swift': '迅捷',
    'armed': '装甲',
    'chest': '箱',
    'corruption': '腐化',
    'demand': '欲望',
    'reinforce': '强化',
    'lifelong': '长命',
    'elite': '精英',
    'summon': '召唤',
    'kill': '击败',
    'summon and kill': '召唤并击败',
    'recipe': '配方',
    'recipes': '配方',
    'endless': '无尽',
    'fireball': '火球',
    'dragon': '龙',
    'dragon scale': '龙鳞',
    'a ': '一个',
    'especially': '尤其',
    'resistant to': '能够抵抗',
    'light': '光',
    'fire': '火',
    'ice': '冰',
    'fire quench: dragon': '火龙淬：',
    'ice quench: dragon': '冰龙淬：',
    'dark quench: dragon': '暗龙淬：',
    'light quench: dragon': '光龙淬：',
    'swift sword': '西洋剑',
    'octave': '八度',
    'when first hit': '首次击中时',
    'get back': '返还',
    'of': '',
    'gain ally with': '增益我方',
    'dragon breath': '龙息',
    'lv.i': '壹階',
    'lv i': '壹階',
    'lv.ii': '贰階',
    'lv ii': '贰階',
    'lv.iii': '叁階',
    'lv iii': '叁階',
    'lv.iv': '肆階',
    'lv iv': '肆階',
    'lv.v': '伍階',
    'lv v': '伍階',
    'lv.vi': '陆階',
    'lv vi': '陆階',
    'lv.vii': '柒階',
    'lv vii': '柒階',
    'lv.xx': '终階',
    'lv xx': '终階',

    'a line start, a god\'s fall': '一语起，一神落',
    'magister': '魔导师',
    'shoots': '发射',
    'a row of': '一行',
    'the ruling sword': '裁决之剑',
    'very': '非常',
    'increase your': '提升',
    'mentality': '精神力',
    'additional': '额外',
    'maximum': '最大',
    'hero shaped': '英雄形状的',
    'recover': '回复',
    'and': '并,',
    'add': '新增',
    'joker evil': '小丑魔',
    'poet bonus': '游吟诗人增益',
    'worldsaver': '救世者',
    'hallow': '神圣',
    'pacify': '安抚',
    'it can save the world': '它可以拯救世界',
    'chaos': '混沌',
    'virus defeater': '病毒战胜者',
    'attack': '攻击',
    'earth': '土',
    'obsidian': '黑曜石',
    'magnificent': '壮丽',
    'natural': '自然',
    'ignite': '点燃',
    'air': '风',
    'thief': '盗贼',
    'small': '小型',
    'tower shield': '塔型盾',
    'gorgeous': '绝美',
    'forest': '森林',
    'coniferous': '针叶',
    'fur': '毛皮',
    'several': '数个',
    'each': '每个',
    'dealing': '造成',
    'reap': '收割',
    'abyss sever': '截渊者',
    'sunrise': '日出',
    'gaia': '盖亚',

    'developer tool': '开发工具',
    'null': '空',
    'coral reef': '珊瑚礁',
    'flufffur': '毛毛毛',
    'otherworld': '异界',
    'stone': '石',
    'scorch': '炽耀',
    'soulfeather': '铸魂翎羽',
    'murder\'s knife': '屠杀者之刃',
    'heavy': '重',
    'no fountain': '虚无喷泉',
    'wingblade': '翼刃',
    'tearblade': '泪刃',
    'swwwword': 'jjjj剑',
    'mantle': '地幔',
    'dim': '暗淡',
    'heavysword': '重剑',
    'doctor expeller': '医生驱逐者',
    'glacier': '冰川',
    'forbidden oath': '誓约与禁忌之刃',
    'wooden club': '大木棍',
    'fiery iceberg': '灼热冰川',
    'devourer': '吞食者',
    'leavigour': '叶魄',
    'cosmos': '鸿蒙',
    'ark of elements': '元素方舟',
    'milky way': '银河',
    'lily of the valley': '谷中铃兰',
    'dream violet': '梦之紫罗兰',
    'void': '虚无',
    'fate': '命途',
    'star\'s defense': '群星之护',
    'quark rusher': '夸克突进者',
    'spike': '刺',
    'valkyrien': '瓦尔基里',
    'seaprick': '海刺',
    'poseidon': '波塞冬',
    'world bow': '世界之弓',
    'kuangkuangkuang': '哐哐哐哐',
    'forget': '遗忘',
    'aiolos': '艾奥莉斯',
    'celestic': '星穹',
    'world\'s bow': '世界之弓',
    'gaze': '凝视',
    'phoenix': '凤凰',
    'exploder': '爆破者',
    'minishark': '迷你鲨',
    'witness': '目击',
    'shark': '鲨',
    'fire shine': '炎耀',
    'demolisher': '破坏者',
    'frozen fire': '霜焱',
    'pro max': 'PRO MAX',
    'dagger': '匕首',
    'double': '双',
    'generation': '传代',
    'shuriken': '手里剑',
    'ball': '球',
    'spikeball': '刺球',
    'grenade': '手雷',
    'jade grenade': '玉手雷',
    'jade mask': '玉面',
    'cactus': '仙人掌',
    'genuine': '正版',
    'air float': '空浮',
    'nameless': '无名',
    'isobar': '等压',
    'tornado': '龙卷风',
    'tropical cyclone': '热带气旋',
    'dydy': 'S',
    'water of disability': '残疾之水',
    'time lily': '时序彼岸花',
    'growth': '生长',

    'the proof of embracing eternity': '拥抱永恒的证明',

    'fluffy': '毛绒',
    'fairy': '仙灵',
    'hermes': '赫尔墨斯',
    'grenade king': '手雷王',
    'jade face': '玉面',
    'enable': '启用',
    'scattering': '散射',
    'dawn': '黎明',
    'shortsword': '短剑',
    'twilight': '暮光',
    'twinsword': '双剑',
    'twinblade': '双刃',
    'broadsword': '阔剑',
    'soarer': '翱翔者',
    'destroy': '摧毁',
    'enhance': '提升',
    'to ': '以',
    'make it under': '使其在于',
    'death': '死亡',
    'life': '生命',
    'broken': '破损',
    'guardian': '守卫者',
    'star': '星',
    'glowing': '闪耀',
    'in ': '于',
    'tough': '坚硬',
    'forward': '脉冲',
    'water': '水',
    'not the others': '无他',
    'pong': '乒乒乓乓',
    'nobody left': '无人生还',
    'empty': '空',
    'shotgun': '霰弹枪',
    'three': '三个',
    'thousand': '千',
    'ignore': '忽略',
    'justice': '正义',
    'justice shot': '正义之枪',
    'chlorophyte': '叶绿',
    'lazer': '激光',
    'prism': '棱镜',
    'light focus': '光聚焦',
    'talent': '智力',
    'god': '神',
    'space': '空间',
    'all': '全部',
    'photon': '光子',
    'thorn': '荆棘',
    'super': '超',
    'thinking': '思想',
    'demon': '恶魔',
    'rune': '符文',
    'lifebringer': '生命使者',
    'great': '大',
    'remote': '远程',
    'mighty': '伟大',
    'of this blade is not necessary to say': '于这把剑中无需多言',
    'terror': '恐怖',
    'primal': '原初',
    'circulate': '循环',
    'domain': '领域',
    'determined': '决心',
    'determination': '决心',
    'matter': '物质',
    'ultradense': '致密',
    'your': '',
    'footprint': '足迹',
    'will': '会',
    'deal': '造成',
    'willpower': '意志',
    'ultra-lightspeed': '超光速',
    'beyond horizon': '视界之外',
    'karmic trail boots': '因果循迹重靴',
    'grasp of the infinite corridor': '无尽回廊之握',
    'fate alignment amulet': '命运校准护身符',
    'my locket': '我的挂坠盒',
    'my': '我的',
    'galaxy broad sword': '星河大剑',
    'eternal echo': '永恒回响',
    'musician': '音乐家',
    'phantom': '幻影',
    'sight': '视力',
    'essence of': '精华来自于',
    'strong': '强大',
    'church': '教堂',
    'colourful': '多彩',
    'strength': '力量',
    'wither': '凋零',
    'cold': '冰冷',
    'mind': '心灵',
    'cyber': '赛博',
    'dragon bone': '龙骨',
    'dragon skull': '龙颅',
    'dragon heart': '龙心',
    'bone': '骨',
    'skull': '颅',
    'merged metal': '融合金属',
    'finale': '大结局',
    'godkiller': '弑神者',
    'legging': '护腿',
    'headgear': '头饰',
    'mask': '面具',
    'plate mail': '板甲',
    'chestplate': '胸甲',
    'greaves': '护腿',
    'abyss': '深渊',
    'twin': '双子',
    'godfall': '神陨',
    'ice and fire': '冰与火',

    'ignis': '伊格尼斯',
    'scorching wing': '炽焰之翼',
    'northrend': '诺森德',
    'frost breath': '极寒之息',
    'nefarian': '纳法利安',
    'shadow embrace': '暗影之拥',
    'olivia': '奥利维亚',
    'radiance of light': '圣光之耀',
    'cybress': '赛博斯',
    'iron heart': '钢铁之心',
    'eonar': '艾诺尔',
    'whisper of mind': '心灵之语',
    'thing': '事物',
    'pickaxe': '镐',
    'critical': '暴击',
    'faith': '「信」',
    'clock': '「时」',
    'matters': '「物」',
    'the world\'s tree': '「世界之树」',
    'reincarnation': '轮回',
    'god\'s eye': '「神之眼」',

    'eternal hush': '永寂渊声',
    'voidstride treads': '渊行履迹',
    'vermillion sigil palms': '赤曜纹枢',
    'aurora dawn': '启明渊声',

    'air resistance': '空气阻力',
    'wing control': '翅膀控制',
    'walking tree': '行走之树',
    'chance': '机会',
    'save a ammo': '保存弹药',
    'reduce': '减少',
    'be ': '',
    'default': '一般',
    'common': '普通',
    'uncommon': '稀有',
    'rare': '罕见',
    'very rare': '非常罕见',
    'proficiency-made': '专家之作',
    'epic': '史诗',
    'legendary': '传说',
    'masterwork': '大师之作',
    'supreme': '至尊',
    'mythic': '神话',
    'super mythic': '超神话',
    'godlike': '神级',
    'super godlike': '超神级',

    'the fluffy worm': '毛绒的蠕虫',
    'the watcher of terror': '恐怖的守望者',
    'the god\'s heritage': '神的遗物',
    'the fire monster': '火焰的怪物',
    'the ghost of desert': '沙漠的幽魂',
    'the dimensional intruder': '次元的入侵者',
    'the contanminated destroyer': '腐化的毁灭者',
    'the cursed fairy': '诅咒的仙灵',
    'the ghost of the snowland': '极地的幽魂',
    'fire dragon': '火龙',
    'ice dragon': '冰龙',
    'dark dragon': '暗龙',
    'light dragon': '光龙',
    'mechanic dragon': '械龙',
    'mind dragon': '灵龙',
    'the heaven intruder': '天堂的入侵者',
    'the non-believer': '不实者',
    'the dishonester': '不诚者',
    'the metal worm of strength': '强力的金属虫',
    'the electric lier': '电子欺诈者',
    'the final mechanic': '最终的机械',
    'the greedy biter': '贪婪的啃食者',
    'follower of the truth': '真理的信徒',
    'the world\'s devourer': '世界的吞噬者',
    'the chaos laughter': '混乱的笑柄',
    'the semi-god': '半神',
    'the watcher of ages': '岁月的守望者',
    'the constructor': '初诞者',
    'sun and moon': '日与月',
    'the unwill of the supreme': '至高的不甘',
    'the end of shapeless': '无形的尽头',
    'the void and chaos': '虚无与混沌',

    'oblivion: annihilator': '终焉：湮灭之主',
    'end\'s sphere': '末世之球',
    'burst ball': '爆裂球',
    'crush ball': '碎裂球',

    'tip': '纸条',
    'done': '完成',
    'map': '地图',
    'weapon sweep': '武器扫荡',
    'image': '图像',
    'mem': 'MEM',
    'saving': '保存',
    'entity': '实体',
    'require': '需要',
    'any': '任何',
    'out': '出',
    'item': '物品',
    'collection': '收集',
    'fps': 'FPS',
    'x': 'x',
    'agility': '敏捷',
    'cd': 'CD',
    'deg': '度',
    'kg': '千克',
    'ize': '化',
    'good': '好',
    'rapid': '密集',
    'rocket': '火箭',
    'launcher': '发射器',
    'ammo': '弹药',
    'thrower': '投掷者',
    'you': '你',
    'improve': '改善',
    'd ': '',
    'save': '节省',
    'ness': '',
    'glow spawn': '火花',
    'traveller boots': '旅者靴',
    'bomb': '弹',
    'charm': '护符',
    'auto-': '自动',
    'key:': '键位:',
    'causing potion sickness': '造成抗药性',
    'potion sickness': '抗药性',
    'when': '当',
    'doubleknife': '双刀',
    'smart ball': '智慧之球',
    'anklet': '脚镯',
    'see': '看',
    'not afraid': '不畏',
    'never lies': '不言假',
    'mercy': '仁慈',
    'size': '大小',
    'flame': '烈焰',
    'sweeping': '横扫时',
    'press': '按下',
    'pike': '矛',
    'weapon': '武器',
    'use': '使用',
    'twice': '两次',
    'fur spear': '毛矛',
    'coniferous leaf': '针叶',
    'ice blast': '冰霜冲击',
    'condense': '凝',
    'enables': '启用',
    'aiming to menaces': '对威胁的瞄准指向',
    'sprint back': '向后冲刺',
    'gives target to': '使目标着',
    'unbelievable': '不可思议的',
    'boots': '靴子',
    'blast': '冲击',
    'heals': '治疗',
    'sunset has gone': '日当已落',
    'it\'s now night': '永夜已至',
    'midnight spell': '午夜之术',
    'there\'s': '有',
    ', there\'s dark': '，便有暗',
    'before night, after night': '夜幕降临之前，繁星黯淡之后',
    'use 20 times': '使用20倍',
    'projectiles to enemies': '子弹攻击敌人',
    'snow': '雪',
    'snow wings': '雪之翼',
    '3 times': '三倍',
    'something': '某物',
    'will happen': '将会发生',
    'potion': '药水',
    'mithrill anvil': '秘银砧',
    'resonancer': '共鸣器',
    'the power of evil and the hallow are balanced': '邪恶与神圣的力量平衡',
    'corrupt': '腐蚀',
    'evil corrupted, all in chaos': '恶蚀，一切混乱',
    'find that old god to enhance': '寻找古神来增强',
    'sacrifice': '献祭',
    'soul of strong flying creatures': '强大飞行生物的灵魂',
    'stab': '攻击',
    'power of honest being': '诚实之力',
    'magic circle': '法阵',
    'unregretted': '不悔',
    'choice': '选择',
    'is right': '永远正确',
    'power of fearless': '无畏之力',
    'gloves': '手套',
    'arrows': '箭',
    'by hand': '',
    'power of mercy': '仁慈之力',
    'contained unparalleled energy': '容纳无与伦比的能量',
    'inviolable': '不容侵犯的',
    'ghost\'s blade': '鬼刃',
    'max': '最大',
    'knowledge': '知识',
    'power of hope': '希望之力',
    'worn': '破旧',
    'notebook': '笔记本',
    'time adjust': '时间校正',
    'toy': '玩具',
    'gather': '收集',
    'power of fairness': '公正之力',
    'millennium persists': '千年不变',
    'thousands of years non-stopping': '千年不息',
    'attracts enemies': '吸引敌人',
    'power of endurance': '忍耐之力',
    'why a ranger should stand close': '远程站那么近干什么',
    'shoot 3 times': '连射3发',
    'stand closer?': '靠近点？',
    'soul of growth': '生长之魂',
    'soul of strong growing creatures': '强大成长之物的灵魂',
    'soul of coldness': '寒冷之魂',
    'soul of strong chilling creatures': '强大寒冷之物的灵魂',
    'bow of sanction': '审判之弓',
    'chlorophyll': '叶绿素',
    'carry out': '产生',
    'photosynthesis': '光合作用',
    'something left after death': '某物死后留下的东西',
    'cuts lifeless lines': '切下毫无生命的线条',
    'rain': '雨',
    'sniper': '狙击枪',
    'energetic': '能量',
    'astigmatism': '散光',
    'chloro': '叶绿',
    'always face to target': '始终面向目标',
    'necklace of life': '生命项链',
    'fruit': '果',
    'cowboy': '牛仔',
    'cloudy glasses': '模糊的眼镜',
    'space jumper': '空间跳跃者',
    'teleporter': '传送器',
    'killer': '杀手',
    'teleport': '传送',
    'skyfire': '天火',
    'meteor': '流星',
    'azure': '蔚蓝',
    'guard': '守卫',
    'wall': '墙',
    'bringer': '赐予者',
    'target': '目标',
    'dummy': '假人',
    'judgement': '审判',
    'restrict': '控制',
    'fire seraph': '火之熾天使',
    'full of': '充满',
    'seven': '七',
    'soul\'s': '魂之',
    'wilson': '維多利亞奔騰的駿馬',
    'designed by': '设计灵感来源：',
    'muramasa': '村正',
    'invalid': '无效',
    'flower vase': '花瓶',
    'evileye': '邪眼',
    'lava': '熔岩',
    'walker': '行者',
    'starnight': '星夜',
    'lv.nulla': '原初之階',
    'pseudo': '伪',
    'sun': '日',
    'purify': '净化',
    'essence of continuing': '持续下去的精华',
    'pulse': '脉冲',
    'willpower of non-regretted chooses': '不悔选择的意志',
    'reach': '抵达',
    'limit of human souls': '人类灵魂的极限',
    'change': '改变',
    'instead': '代替之',
    'sandwich': '三明治',
    'origin': '本源',
    'seed of origin': '本源之种',
    'the memory from the old days starts to grow out new leaves': '旧日之回忆渐已长出新芽',
    'seed of laws': '法则之种',
    'inner': '内',
    'probably': '可能',
    'have to': '需要',
    'it': '它',
    'wierd': '诡异',
    'essence': '精华',
    'something strange': '奇怪的东西',
    'closer, scarier': '靠近些，恐怖些',
    'note': '笔记',
    'dark wield': '暗器',
    'moon': '月',
    'save you bake to life': '救你于死地',
    'but': '但是',
    'minutes and hours': '一分一秒',
    'hour hand': '时针',
    'spin': '旋转',
    'stop': '停',
    'altitude': '海拔',
    'no need to say': '不必多言',
    '\'ll': '将',
    'trapped': '被困',
    'it\'s still here': '它仍在',
    'time wheel': '时间轮',
    'when it is constructed': '当它建造时',
    'came': '来',
    'gone': '去',
    'ultimate': '终极',
    'spark light': '火花',
    'using': '使用',
    'weapons': '武器',
    'increase': '增加',
    'by': '',
    'fury': '怒',
    'star wrath': '狂星之怒',
    'every': '所有',
    'almost': '几乎',
    'horizon goggles': '地平线镜',
    'appeal entities': '吸引实体',
    'the most': '最',
    'beautiful': '美丽的',
    'with': '连带',
    'time passing': '时间流逝',
    'time flies': '时间飞逝',
    'hours and hours are flying by': '一天天过去',
    'increase of speed': '加速',
    'near to': '临近',
    'stop time': '暂停时间',
    'explosion': '爆炸',
    'celestial': '天体',
    'stars': '星星',
    'float system': '浮动系统',
    'within': '内含',
    'controller system': '控制系统',
    'pearl': '珍珠',
    'sun pearl': '日珠',
    'scorching': '灼烧',
    'seperator': '分裂者',
    'acid': '酸',
    'my soul, my will': '吾魂，吾魄',
    'you cannot be improved then': '你不能在继续提升了',
    'rudder': '舵',
    'that\'s how to control': '这就是控制的方法',
    'reason': '因',
    'result': '果',
    'where it starts': '起源之处',
    'how it ends': '终结之时',
    'destruct thoughts': '思想解构',
    'i think, i do': '我想，我做',
    'the final': '终焉',
    'no matter the past or the future, you are the immortal being': '不管过去或未来，汝皆不朽',
    'galaxy headbows to you': '银河亦向汝俯首',
    'galaxy ends, with silent echos': '银河之末，沉默的回响',
    'under the star, is all in faith': '星辰之下，信仰闪耀',
    'the unforgettable moment': '难忘之时',
    'the conflict will happen': '冲突会发生',
    'prophecy': '「预言」',
    'it\'s impossible to change': '这无法改变',
    'without determination': '当没有决心时',
    'zenith': '天之穹顶，星之所及',
    'the world admits you': '世界亦承认汝之存在',
    'your damage is restricted toward the weak enemies': '面对弱小的敌人会降低伤害',
    'your power really matters': '你的力量真的很重要',

    'resolution': '「收」',
    'rising action': '「承」',
    'falling action': '「合」',

    'quark_rusher': '夸克突进者',

    'gods are formless': '神本无相',
    'irec': '以睿客',

    'aerialite': '天蓝',
    'coral_reef': '珊瑚礁',
    'forgotten': '遗忘',
    'stele': '碑石',


    'can only be placed in the first slot': '只能放在第一饰品栏',
    'can only be placed in the second slot': '只能放在第二饰品栏',
    "origin feather": "起源之羽",
    "infinitesimal": "零点",
    "hellseal": "镇狱",
    "resistant to perilous biomes, e.g. deserts and snows": "抵抗危险的生物群落，如沙漠和雪原",

    "i": "I",
    "ii": "II",
    "iii": "III",
    "iv": "IV",
    "V": "V",

# Machine Translation
    "find related recipes": "相关食谱：",
    "soul of strong scorching creatures.": "强大灼热生物的灵魂。",
    "with spirit as combinator.": "以灵魂为组合者。",
    "biome alloy": "生物群系合金",
    "power of lifes.": "生命的力量。",
    "immersed in increasing power.": "沉浸于不断增强的力量中。",
    "combination of numberless essences.": "无数精华的组合。",
    "until exceeding the limit of humans.": "直到超过人类的极限。",
    "a spark of light.": "一丝光芒。",
    "oracle": "Oracle",
    "let enemies became burnt under the fire of chaos.": "让敌人在混乱的火焰下燃烧。",
    "enemies becomes less adapted to your power.": "敌人变得不太适应你的力量。",
    "fountain not found": "未找到喷泉",
    "bushi": "BUSHI",
    "sky edge": "Sky Edge",
    "hidden heat": "隐藏的热量",
    "diamond": "钻",
    "ice crystal edge": "冰晶刃",
    "chance to freeze enemies for ": "有概率使敌人冰冻",
    "s.": "s.",
    "viper spiker": "Viper Spiker",
    "the anger from the starry sky.": "星空的怒火。",
    "the divine keeper and ruler of the winds.": "风的神圣守护者和统治者。",
    "when shooting, press q to sprint back.": "拍摄时，按Q向后冲刺。",
    "rapidly shoots a piercive shard.": "迅速射出一个穿刺碎片。",
    "rapid rocket launcher v": "快速火箭发射器v",
    "rocket launcher v": "火箭弹发射器",
    "the jade-masked grenade king.": "玉面手榴弹王。",
    "half the damage range of grenades": "手榴弹伤害范围的一半",
    "energy magic lv.iii: mana spikes": "能量魔法III级：法力尖刺",
    "secondarily": "其次 – ",
    "fire magic lv.xx: nettle burst": "火焰魔法XX级：荨麻爆发",
    "primarily": "首先是：",
    "cloudcore staff": "Cloudcore员工",
    "water magic lv.iii: cloud mutant": "水之魔法LV.III ：云之变种人",
    "circulate attract": "Circulate Attract",
    "air magic lv.nulla: circulate's domain: attract": "AIR MAGIC LV.NULLA ： Circulate的领域：吸引",
    "energy magic lv.xxv: energy pulse": "能量魔法LV.XXV ：能量脉冲",
    "relevation of cycles": "周期相关性",
    "light magic lv.xxv: pseudo sun": "光魔法LV.XXV ：伪太阳",
    "circulate repel": "循环排斥",
    "air magic lv.nulla: circulate's domain: repel": "AIR MAGIC LV.NULLA: Circulate领域：击退",
    "muse core": "Muse核心",
    "the core of art": "艺术的核心",
    " range damage": "受损范围",
    "firy greaves": "Firy Greaves",
    "firy mask": "Firy Mask",
    "firy helmet": "Firy头盔",
    "chloro. formal hat": "Chloro.正式帽子",
    "thief's socks": "小偷的袜子",
    "increases ranged damage by ": "远程伤害提升",
    "war necklace": "战争项链",
    "fearful necklace": "恐惧项链",
    "herme's boots": "爱马仕靴子",
    "quenched cross": "淬火十字",
    "immune to bleeding": "免疫出血",
    " biome friction effect": "生物群系摩擦效应",
    "increases ": "涨幅详情",
    "sanctuary": "圣所",
    "summon a pair of eyes, shoots lazer.": "召唤一双眼睛，射出懒惰。",
    "angels amulet": "天使护身符",
    "allows using ": "允许使用",
    "shift": "SHIFT（更改字符类型）",
    " to control speed": "控制速度",
    "speed addons are disabled.": "速度插件已禁用。",
    "naturalify necklace": "归化项链",
    "immune to effects dealt in the overworld.": "对凌驾世界的效果免疫。",
    "reduced effects dealt by abyss.": "减少深渊造成的影响。",
    "s cd": "s CD",
    "bezoar necklace": "牛头怪项链",
    " poison damage received": "受到中毒伤害",
    " poison defense": "中毒防御",
    " additipnal maximum mana": "additipnal最大法力",
    "demon contract": "恶魔契约",
    "save you back to life, but curse you. ": "拯救你的生命，但诅咒你。",
    "eternal wings": "永恒火之翼",
    "eternal pocket watch": "永恒怀表",
    " damage absorb": "损伤吸收",
    "allow acceleration to infinite speed.": "允许加速到无限速度。",
    "all entities' speed to you is too slow.": "所有实体对您的速度都太慢。",
    "a world, a planet, is all in my hand.": "一个世界，一个星球，都在我的手中。",
    "when using melee to hit enemy, deal additionally ": "使用近战击中敌人时，额外造成",
    "prints down the path of karma.": "印下业力之路。",
    "the path of destiny.": "气运之道",
    "revive after death.": "死后复活。",
    "cool it down, and wait.": "冷静下来，然后等待。",
    "say the right words, do the right thing.": "说正确的话，做正确的事。",
    "x of mana cost of current weapon, summoning ": "当前武器法力消耗的x ，召唤",
    "grey hood": "灰兜帽",
    "instrument belt": "仪器传送带",
    "you can feel it beating": "你可以感觉到它在跳动",
    "a book of musical notes you might find useful.": "一本您可能会发现有用的音符书。",
    "the righteousness of the law.": "律法的公义。",
    "kindness amulet": "善良护身符",
    "y: heal everyone until your hp max out": "Y ：治疗所有人，直到你的生命值达到极限",
    "y: attack for ": "Y ：攻击为",
    "x the speed of the current weapon for a moment, ": "x当前武器的速度一会儿，",
    "red algae": "紅藻門",
    "glimmer stone": "微光石",
    "opens a new appearance of your world.": "打开你的世界的新面貌。",
    "shoots arrows by your hand.": "用你的手射箭。",
    "ballet shoes": "芭蕾舞鞋",
    "delicious seedling": "美味的幼苗",
    "summon python": "召唤巨蟒",
    "summon glimmer skate in fallen sea": "在沉陨之海中召唤微光曙鳐",
    "summon balrog in hell": "在地狱中召唤炎魔",
    "this is just made by metals combining together.": "这只是由金属结合在一起制成的。",
    "summon the mechanic medusa.": "召唤机械师美杜莎。",
    "summon the devil python": "召唤魔蟒",
    "summon the cpu": "召唤计划工作站",
    "summon the sky tri-cubes": "召唤天空三角形",
    "summon dragons around the world.": "召唤世界各地的龙。",
    "summon the polar cube": "召唤极地魔方",
    "poison horn": "毒角",
    "summon the naga": "召唤那迦",
    "compass": "指南针",
    "where is it leading you to?": "它会带您去哪里？",
    "take you to path.": "带你走上正轨。",
    "key:h": "钥匙： H",
    " hp and adds a ": "生命值并增加",
    "obsidian polearm": "黑曜石极臂",
    "swinging and swinging, and then fall asleep.": "摇摆摇摆，然后入睡。",
    "the basic unit of music.": "音乐的基本单位。",
    "hand of pacify": "安抚之手",
    "'z'": "2",
    "z..z..z..": "Z.. z.. Z..",
    "they always say it as they fall asleep.": "他们总是在睡觉时说。",
    "extinct": "灭绝",
    "lychee core": "荔枝芯",
    "immune potion": "免疫药剂",
    "provides a about ": "提供关于",
    "s immune time, but damage were dealt.": "的免疫时间，但造成伤害。",
    "immediately repels nearby enemies.": "立即击退附近的敌人。",
    "key:m": "Key: M",
    "recovers ": "回复了",
    "tension bit": "张力钻头",
    "heart pie": "心形派",
    "duration: ": "长度：",
    "s": "s",
    "toilet paper": "厕纸",
    "recover all tp": "恢复所有",
    "where is it going to lead you?": "它会带你去哪里？",
    "endless power of ice.": "冰的无尽力量。",
    "ice dragon breath wand": "寒冰龙息",
    "water magic lv.vii: ice dragon's breath": "水之魔法LV.VII ：冰龙之息",
    "fire dragon breath wand": "火龙呼吸棒",
    "fire magic lv.vii: fire dragon's breath": "火焰魔法LV.VII ：火龙之息",
    "endless power of darkness.": "无尽的黑暗力量。",
    "endless power of light.": "无穷无尽的光明之力。",
    "a unit that can cool down minds.": "一个可以冷静下来的单位。",
    "a unit that can heat up light.": "可以加热光线的设备。",
    "a unit that can heat up darkness.": "一个可以加热黑暗的单位。",
    "a unit that can heat up ice.": "可以加热冰的装置。",
    "a unit that can heat up fire.": "可以加热火焰的装置。",
    "your body protects you from death.": "你的身体保护你免于死亡。",
    "your footprint weakens the enemies.": "你的脚印会削弱敌人。",
    "your move cause your surrounding will be frozen.": "你的举动会导致周围环境冻结。",

}
