# Underia Mod Setup
# Auto generated by src.mods.setup.underia_mod_setup()
# Copyright klpig 2024, all rights not reserved.

import underia, mods
import pygame as pg

# Basic datas
MOD_NAME = 'Text-ure'
MOD_VERSION = (1, 0, 0)
MOD_AUTHOR = 'KLpig'
MOD_DESCRIPTION = 'Text images(physically)'

# Mod Contents
ITEMS: dict[str, underia.Inventory.Item] = {
	
}
RECIPES: list[underia.Recipe] = [
	
]
WEAPONS: dict[str, underia.Weapon] = {
	
}
PROJECTILE_TYPE = type(underia.Projectiles.Projectile)
PROJECTILES: dict[str, PROJECTILE_TYPE] = {
	
}
ENTITY_TYPE = type(underia.Entities.Entity)
ENTITIES: dict[str, ENTITY_TYPE] = {
	
}

# SETUP_FUNC
# Code here (import allowed)
try:
    graphics = underia.get_game().graphics

    font = pg.font.SysFont('papyrus', 180)

    for k, v in graphics.graphics.items():
        sx, sy = 128, 128
        fr = font.render(k.split('_')[-1], True, (255, 255, 255), (0, 0, 0))
        fr = pg.transform.scale(fr, (sx, fr.get_height() * sx / fr.get_width()))
        surf = pg.Surface((sx, sy), pg.SRCALPHA)
        frr = fr.get_rect()
        frr.center = surf.get_rect().center
        surf.blit(fr, frr)
        graphics.graphics[k] = surf
except ValueError:
    pass
# SETUP_FUNC
# UPDATE_FUNC
# Code here (import allowed)
# UPDATE_FUNC
mods.wrap()