# Underia Mod Setup
# Auto generated by src.mods.setup.underia_mod_setup()
# Copyright klpig 2024, all rights not reserved.

from src import underia, mods

# Basic datas

MOD_NAME = 'Full Item Maker'
MOD_VERSION = (1, 0, 0)
MOD_AUTHOR = 'KLPig'
MOD_DESCRIPTION = 'Get full items by crafting'

# Mod Contents
ITEMS: dict[str, underia.Inventory.Item] = {

}
RECIPES: list[underia.Recipe] = [

]
WEAPONS: dict[str, underia.Weapon] = {

}
PROJECTILE_TYPE = type(underia.Projectiles.Projectile)
PROJECTILES: dict[str, PROJECTILE_TYPE] = {

}
ENTITY_TYPE = type(underia.Entities.Entity)
ENTITIES: dict[str, ENTITY_TYPE] = {

}


# SETUP_FUNC
# Code here (import allowed)
from src import underia
print('Full Item Maker Setup')
underia.RECIPES.clear()
for item in underia.ITEMS.values():
    underia.RECIPES.append(underia.Recipe({}, item.id))
# SETUP_FUNC
print(underia.RECIPES)
# UPDATE_FUNC
# Code here (import allowed)
# UPDATE_FUNC
mods.wrap()