# Underia Mod Setup
# Auto generated by src.mods.setup.underia_mod_setup()
# Copyright klpig 2024, all rights not reserved.

import underia, mods

# Basic datas
MOD_NAME = 'Test mod'
MOD_VERSION = (1, 0, 0)
MOD_AUTHOR = 'Klpig'
MOD_DESCRIPTION = 'This is a test mod.'

# Mod Contents
ITEMS: dict[str, underia.Inventory.Item] = {
	'test_item': underia.Inventory.Item('Test Item', 'This is a test item.', 'test_item',
                                        tags=[underia.TAGS['item']])
}
RECIPES: list[underia.Recipe] = [
	underia.Recipe({'wood': 1}, 'test_item'),
]
WEAPONS: dict[str, underia.Weapon] = {
	
}
PROJECTILE_TYPE = type(underia.Projectiles.Projectile)
PROJECTILES: dict[str, PROJECTILE_TYPE] = {
	
}
ENTITY_TYPE = type(underia.Entities.Entity)
ENTITIES: dict[str, ENTITY_TYPE] = {
	
}

mods.wrap()